// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmf1ALtEPxlbUOBK2jLgoRgdHLo3TZk_4',
    appId: '1:689526002720:web:0824e423d2fc8c8bbb9845',
    messagingSenderId: '689526002720',
    projectId: 'carwashapp-df53b',
    authDomain: 'carwashapp-df53b.firebaseapp.com',
    storageBucket: 'carwashapp-df53b.appspot.com',
    measurementId: 'G-RFFBDVGJWW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbhIGsJeZAowM8EoxKeSIdPKRrCsvC4W0',
    appId: '1:689526002720:android:2ee97fc555586c7ebb9845',
    messagingSenderId: '689526002720',
    projectId: 'carwashapp-df53b',
    storageBucket: 'carwashapp-df53b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJX8HWHIAI0UY42EvK6XrGNlxslf-Ceek',
    appId: '1:689526002720:ios:08eb57c87bed3baebb9845',
    messagingSenderId: '689526002720',
    projectId: 'carwashapp-df53b',
    storageBucket: 'carwashapp-df53b.appspot.com',
    iosBundleId: 'com.example.carWash',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJX8HWHIAI0UY42EvK6XrGNlxslf-Ceek',
    appId: '1:689526002720:ios:08eb57c87bed3baebb9845',
    messagingSenderId: '689526002720',
    projectId: 'carwashapp-df53b',
    storageBucket: 'carwashapp-df53b.appspot.com',
    iosBundleId: 'com.example.carWash',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmf1ALtEPxlbUOBK2jLgoRgdHLo3TZk_4',
    appId: '1:689526002720:web:70ec02b58ec44dd1bb9845',
    messagingSenderId: '689526002720',
    projectId: 'carwashapp-df53b',
    authDomain: 'carwashapp-df53b.firebaseapp.com',
    storageBucket: 'carwashapp-df53b.appspot.com',
    measurementId: 'G-YR6P3S0TXX',
  );
}
